// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvDnd43mEDyINd6iywh8iNB0XjDStP6Nc',
    appId: '1:498587589209:web:281cb5122ad2e289bc6f48',
    messagingSenderId: '498587589209',
    projectId: 'lpg-finder-ge',
    authDomain: 'lpg-finder-ge.firebaseapp.com',
    storageBucket: 'lpg-finder-ge.firebasestorage.app',
    measurementId: 'G-BTM5KCYZ0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRT5ndwZBFvrq16qfo8TQWdQflYN1qSfQ',
    appId: '1:498587589209:android:2500df4545d28ff8bc6f48',
    messagingSenderId: '498587589209',
    projectId: 'lpg-finder-ge',
    storageBucket: 'lpg-finder-ge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-FFIAdnsBxYMIsN10uiAte6mxTZaCkA',
    appId: '1:498587589209:ios:2e9d66856919f3f1bc6f48',
    messagingSenderId: '498587589209',
    projectId: 'lpg-finder-ge',
    storageBucket: 'lpg-finder-ge.firebasestorage.app',
    iosClientId: '498587589209-uib28npfmc6gm5sjn30kg3iqugbir09p.apps.googleusercontent.com',
    iosBundleId: 'com.example.lpgFinderGe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-FFIAdnsBxYMIsN10uiAte6mxTZaCkA',
    appId: '1:498587589209:ios:2e9d66856919f3f1bc6f48',
    messagingSenderId: '498587589209',
    projectId: 'lpg-finder-ge',
    storageBucket: 'lpg-finder-ge.firebasestorage.app',
    iosClientId: '498587589209-uib28npfmc6gm5sjn30kg3iqugbir09p.apps.googleusercontent.com',
    iosBundleId: 'com.example.lpgFinderGe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvDnd43mEDyINd6iywh8iNB0XjDStP6Nc',
    appId: '1:498587589209:web:d918264c1bd99048bc6f48',
    messagingSenderId: '498587589209',
    projectId: 'lpg-finder-ge',
    authDomain: 'lpg-finder-ge.firebaseapp.com',
    storageBucket: 'lpg-finder-ge.firebasestorage.app',
    measurementId: 'G-HVY6VGS6LP',
  );
}
